#!/usr/bin/env python
# Copyright (c) 2013 Turbulenz Limited
"""
Manage the Turbulenz local development server.
"""

from turbulenz_local.local_server import main

if __name__ == "__main__":
    exit(main())
